# Generated by Django 5.2.7 on 2025-11-05 06:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Conversation', help_text='Title of the conversation', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of the conversation', max_length=1000, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', help_text='Current status of conversation', max_length=20)),
                ('is_pinned', models.BooleanField(default=False, help_text='Whether conversation is pinned to top')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether conversation is archived')),
                ('topic', models.CharField(blank=True, help_text="Main topic of conversation (e.g., 'AI', 'Programming')", max_length=100, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=500, null=True)),
                ('message_count', models.IntegerField(default=0, help_text='Total number of messages in conversation')),
                ('average_sentiment', models.FloatField(default=0.0, help_text='Average sentiment score (-1 to 1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When conversation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When conversation was last updated')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Timestamp of last message', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether conversation is public/shareable')),
                ('share_token', models.CharField(blank=True, help_text='Token for sharing conversation', max_length=32, null=True, unique=True)),
                ('user', models.ForeignKey(help_text='User who owns this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI Assistant'), ('system', 'System')], default='user', help_text='Who sent this message', max_length=20)),
                ('content', models.TextField(help_text='Message content', validators=[django.core.validators.MinLengthValidator(1)])),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('pending', 'Pending')], default='sent', help_text='Delivery status of message', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if message failed', null=True)),
                ('model_used', models.CharField(blank=True, help_text='AI model used to generate response (for AI messages)', max_length=100, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Time taken to generate response (milliseconds)', null=True)),
                ('token_count', models.IntegerField(blank=True, help_text='Number of tokens used', null=True)),
                ('sentiment_score', models.FloatField(default=0.0, help_text='Sentiment score (-1.0 to 1.0)')),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], help_text='Sentiment classification', max_length=20, null=True)),
                ('is_liked', models.BooleanField(default=False, help_text='Whether user liked this message')),
                ('is_disliked', models.BooleanField(default=False, help_text='Whether user disliked this message')),
                ('reaction', models.CharField(blank=True, help_text='User reaction emoji/feedback', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When message was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When message was last updated')),
                ('is_pinned', models.BooleanField(default=False, help_text='Whether message is pinned')),
                ('citations', models.JSONField(blank=True, default=list, help_text='Citations/sources for message')),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('positive_score', models.FloatField(default=0.0, help_text='Probability of positive sentiment (0.0-1.0)', validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1)])),
                ('neutral_score', models.FloatField(default=0.0, help_text='Probability of neutral sentiment (0.0-1.0)', validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1)])),
                ('negative_score', models.FloatField(default=0.0, help_text='Probability of negative sentiment (0.0-1.0)', validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1)])),
                ('label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], help_text='Overall sentiment classification', max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score of classification')),
                ('model_used', models.CharField(default='bert-base-multilingual-uncased', help_text='Sentiment analysis model used', max_length=100)),
                ('analysis_version', models.CharField(default='1.0', help_text='Version of sentiment model', max_length=20)),
                ('emotions', models.JSONField(blank=True, default=dict, help_text='Detected emotions (e.g., joy, anger, fear)')),
                ('key_phrases', models.JSONField(blank=True, default=list, help_text='Key sentiment-bearing phrases')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, help_text='When sentiment analysis was performed')),
                ('conversation', models.ForeignKey(help_text='Parent conversation for analytics', on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analyses', to='conversations.conversation')),
                ('message', models.OneToOneField(help_text='Message being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analysis', to='conversations.message')),
            ],
            options={
                'verbose_name': 'Sentiment Analysis',
                'verbose_name_plural': 'Sentiment Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_topic', models.CharField(help_text='Main topic of conversation', max_length=100)),
                ('secondary_topics', models.JSONField(blank=True, default=list, help_text='List of secondary topics')),
                ('category', models.CharField(help_text="Category classification (e.g., 'Technical', 'General')", max_length=100)),
                ('subcategory', models.CharField(blank=True, help_text='Subcategory if applicable', max_length=100, null=True)),
                ('keywords', models.JSONField(default=list, help_text='List of important keywords')),
                ('entities', models.JSONField(blank=True, default=dict, help_text='Named entities extracted (people, places, organizations)')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence of topic classification (0.0-1.0)')),
                ('model_used', models.CharField(default='zero-shot-classification', help_text='Model used for topic extraction', max_length=100)),
                ('complexity_score', models.FloatField(default=0.0, help_text='Complexity of conversation (0.0-1.0)')),
                ('technical_score', models.FloatField(default=0.0, help_text='How technical the conversation is (0.0-1.0)')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, help_text='When topic analysis was performed')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When topic was last updated')),
                ('conversation', models.OneToOneField(help_text='Conversation being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='topic_analysis', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Topic Analysis',
                'verbose_name_plural': 'Topic Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='conversatio_user_id_a61baf_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='conversatio_status_b2d188_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_pinned'], name='conversatio_is_pinn_c0cc05_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='conversatio_sender_56041f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sentiment_label'], name='conversatio_sentime_a00aca_idx'),
        ),
        migrations.AddIndex(
            model_name='sentiment',
            index=models.Index(fields=['conversation', 'analyzed_at'], name='conversatio_convers_e08e68_idx'),
        ),
        migrations.AddIndex(
            model_name='sentiment',
            index=models.Index(fields=['label'], name='conversatio_label_32516a_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['primary_topic'], name='conversatio_primary_5e4632_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['category'], name='conversatio_categor_ed2bce_idx'),
        ),
    ]
